-- MySQL Script generated by MySQL Workbench
-- Mon Apr 25 18:54:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema examen3_seydilara
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema examen3_seydilara
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `examen3_seydilara` DEFAULT CHARACTER SET utf8 ;
USE `examen3_seydilara` ;

-- -----------------------------------------------------
-- Table `examen3_seydilara`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examen3_seydilara`.`usuario` (
  `Codigo` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  `EstaActivo` TINYINT NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


INSERT INTO `examen3_seydilara`.`usuario` (`Codigo`, `Nombre`, `Rol`, `Clave`, `EstaActivo`) VALUES ('SLARA', 'Seydi Lara', 'Administrador', '123456', '1');
INSERT INTO `examen3_seydilara`.`usuario` (`Codigo`, `Nombre`, `Rol`, `Clave`, `EstaActivo`) VALUES ('NCASCO', 'Nahum Casco', 'Usuario', '123456', '1');
INSERT INTO `examen3_seydilara`.`usuario` (`Codigo`, `Nombre`, `Rol`, `Clave`, `EstaActivo`) VALUES ('JFUENTES', 'Johana Fuentes', 'Usuario', '123456', '0');




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
